### ISSUE TITLE
Installation error, Python 3 syntax

### ISSUE THREAD

**Issue by DanielTakeshi** [IFL-CAMP/easy_handeye#121]
I am attempting to install `easy_handeye` on an Ubuntu 18.04 machine running ROS Melodic.  

Using a fresh `catkin_ws` directory, I git cloned the repo as shown in the README, resulting in this: 

```
seita@TheCat:~/catkin_ws$ ls -lh src/
total 4.0K
lrwxrwxrwx 1 seita seita   50 Nov 30 15:25 CMakeLists.txt -> /opt/ros/melodic/share/catkin/cmake/toplevel.cmake
drwxrwxr-x 7 seita seita 4.0K Dec  2 13:30 easy_handeye
seita@TheCat:~/catkin_ws$ ls -lh src/easy_handeye/
total 36K
drwxrwxr-x 4 seita seita 4.0K Dec  2 13:30 docs
drwxrwxr-x 5 seita seita 4.0K Dec  2 13:30 easy_handeye
drwxrwxr-x 4 seita seita 4.0K Dec  2 13:30 easy_handeye_msgs
-rw-rw-r-- 1 seita seita 7.4K Dec  2 13:30 LICENSE.md
-rw-rw-r-- 1 seita seita  12K Dec  2 13:30 README.md
drwxrwxr-x 5 seita seita 4.0K Dec  2 13:30 rqt_easy_handeye
```

Then I followed the instructions to try and satisfy the dependencies:

```
seita@TheCat:~/catkin_ws$ rosdep install -iyr --from-paths src
executing command [sudo -H pip2 install -U transforms3d]
Collecting transforms3d
  Downloading https://files.pythonhosted.org/packages/05/bb/6d9bc2d2cc82c7984e0c6af586e561e8ca2e9e641483e617bbd256e5a8da/transforms3d-0.4.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 716kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-A8byOm/transforms3d/setup.py", line 8, in <module>
        import versioneer
      File "versioneer.py", line 370
        LONG_VERSION_PY: Dict[str, str] = {}
                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-A8byOm/transforms3d/
ERROR: the following rosdeps failed to install
  pip: command [sudo -H pip2 install -U transforms3d] failed
  pip: Failed to detect successful installation of [transforms3d]
seita@TheCat:~/catkin_ws$ 
```

However the error is showing that it is a Python3 syntax issue. Is this because `transforms3d` as of 09/01/2022 no longer supports Python 2? https://pypi.org/project/transforms3d/0.4.1/

If so what is the way to adjust the `rosdep` to use `transforms3d==0.3.1`? Thanks.

**Comment by marcoesposito1988** [comment]
Hi @DanielTakeshi,

Yes that looks good
