### ISSUE TITLE
rqt_calibrationmovements `Plan` failed

### ISSUE THREAD

**Issue by julyfun** [IFL-CAMP/easy_handeye#139]
## Environment

- os: ubuntu20.04
- ros: noetic
- date: 24.4.23
- device: Azure kinetic + **UR10**

Clicking the `Plan` button gives an error in the commandline (see below), but it actually got a plan which is only visible in the rviz model (with a planning trajectory animation), but still the `rqt_calibrationmovements` windows shows `No plan yet` and the `Execute` button is in invalid state. 

It seems to be caused by the different lengths of the two joins limit variables. The error message:

```
Traceback (most recent call last):
  File "/home/user/catkin_ws/src/easy_handeye/rqt_easy_handeye/src/rqt_easy_handeye/rqt_calibrationmovements.py", line 123, in handle_check_current_state
    res = self.handeye_client.check_starting_pose()
  File "/home/user/catkin_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_client.py", line 103, in check_starting_pose
    return self.check_starting_pose_proxy()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    responses = transport.receive_once()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 742, in receive_once
    p.read_messages(b, msg_queue, sock) 
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 360, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 343, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
rospy.service.ServiceException: service [/ur10_k4a_handeyecalibration_eye_on_base/check_starting_pose] responded with an error: b'error processing request: operands could not be broadcast together with shapes (8,) (7,) '
```

**Comment by marcoesposito1988** [comment]
Hi @julyfun,

I can't reproduce the issue. Do you have a custom URDF?
