### ISSUE TITLE
Take sample error

### ISSUE THREAD

**Issue by rangfeng1** [IFL-CAMP/easy_handeye#140]
[ERROR] [1715408118.568668, 705.285000]: Error processing request: Lookup would require extrapolation into the past.  Requested time 685.184000000 but the earliest data is at time 1715408108.476723909, when looking up transform from frame [zed_camera_marker] to frame [zed_camera_center]
['Traceback (most recent call last):\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 633, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/wxj/ros_ws_2/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_server.py", line 38, in take_sample\n    self.calibrator.take_sample()\n', '  File "/home/wxj/ros_ws_2/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_calibrator.py", line 134, in take_sample\n    transforms = self._get_transforms()\n', '  File "/home/wxj/ros_ws_2/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_calibrator.py", line 124, in _get_transforms\n    rospy.Duration(20))\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/buffer.py", line 87, in lookup_transform\n    return self.lookup_transform_core(target_frame, source_frame, time)\n', 'ExtrapolationException: Lookup would require extrapolation into the past.  Requested time 685.184000000 but the earliest data is at time 1715408108.476723909, when looking up transform from frame [zed_camera_marker] to frame [zed_camera_center]\n']
Traceback (most recent call last):
  File "/home/wxj/ros_ws_2/src/easy_handeye/rqt_easy_handeye/src/rqt_easy_handeye/rqt_easy_handeye.py", line 108, in handle_take_sample
    sample_list = self.client.take_sample()
  File "/home/wxj/ros_ws_2/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_client.py", line 34, in take_sample
    return self.take_sample_proxy().samples
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    responses = transport.receive_once()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 742, in receive_once
    p.read_messages(b, msg_queue, sock) 
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 360, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 343, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
rospy.service.ServiceException: service [/sawyer_realsense_handeyecalibration_eye_on_base/take_sample] responded with an error: error processing request: Lookup would require extrapolation into the past.  Requested time 685.184000000 but the earliest data is at time 1715408108.476723909, when looking up transform from frame [zed_camera_marker] to frame [zed_camera_center]
[sawyer_zed_eye_on_base/namespace_wxj_vpc_16711_6098393655710652471_rqt-8] process has died [pid 16770, exit code -6, cmd /opt/ros/melodic/lib/rqt_gui/rqt_gui --clear-config --perspective-file /home/wxj/ros_ws_2/src/easy_handeye/easy_handeye/launch/rqt_easy_handeye.perspective __name:=namespace_wxj_vpc_16711_6098393655710652471_rqt __log:=/home/wxj/.ros/log/298b300a-0f5c-11ef-8600-f8a2d6d5c54d/sawyer_zed_eye_on_base-namespace_wxj_vpc_16711_6098393655710652471_rqt-8.log].
log file: /home/wxj/.ros/log/298b300a-0f5c-11ef-8600-f8a2d6d5c54d/sawyer_zed_eye_on_base-namespace_wxj_vpc_16711_6098393655710652471_rqt-8*.log

**Comment by Gritsua** [comment]
hi， Have you solved this problem?
