### ISSUE TITLE
troubles when take sample

### ISSUE THREAD

**Issue by fancangning** [IFL-CAMP/easy_handeye#144]
when I pressed the "take sample"  button, the error appeared.

[ERROR] [1730221145.813726]: Error processing request: Lookup would require extrapolation 0.163575172s into the past.  Requested time 1730221135.660337687 but the earliest data is at time 1730221135.823912859, when looking up transform from frame [aruco_marker_frame] to frame [camera_link]
['Traceback (most recent call last):\n', '  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 633, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/fancangning/catkin_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_server.py", line 88, in take_sample\n    self.sampler.take_sample()\n', '  File "/home/fancangning/catkin_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_sampler.py", line 88, in take_sample\n    transforms = self._get_transforms()\n', '  File "/home/fancangning/catkin_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_sampler.py", line 76, in _get_transforms\n    opt = self.tfBuffer.lookup_transform(self.handeye_parameters.tracking_base_frame,\n', '  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_ros/buffer.py", line 90, in lookup_transform\n    return self.lookup_transform_core(target_frame, source_frame, time)\n', 'tf2.ExtrapolationException: Lookup would require extrapolation 0.163575172s into the past.  Requested time 1730221135.660337687 but the earliest data is at time 1730221135.823912859, when looking up transform from frame [aruco_marker_frame] to frame [camera_link]\n']
Traceback (most recent call last):
  File "/home/fancangning/catkin_ws/src/easy_handeye/rqt_easy_handeye/src/rqt_easy_handeye/rqt_easy_handeye.py", line 132, in handle_take_sample
    sample_list = self.client.take_sample()
  File "/home/fancangning/catkin_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_client.py", line 76, in take_sample
    return self.take_sample_proxy().samples
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    responses = transport.receive_once()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 742, in receive_once
    p.read_messages(b, msg_queue, sock) 
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 360, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 343, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
rospy.service.ServiceException: service [/panda_eob_calib_eye_on_hand/take_sample] responded with an error: b'error processing request: Lookup would require extrapolation 0.163575172s into the past.  Requested time 1730221135.660337687 but the earliest data is at time 1730221135.823912859, when looking up transform from frame [aruco_marker_frame] to frame [camera_link]'

How can I solve this problem?Thank you

**Comment by marcoesposito1988** [comment]
Hi @fancangning,

this may happen if the marker is no more visible when you press the button. An old transform lingers in the tf buffer but easy-handeye avoids to use it as it would lead to a wrong calibration result
