### ISSUE TITLE
Cannot take samples 

### ISSUE THREAD

**Issue by DimitrisKld** [IFL-CAMP/easy_handeye#16]
Hello, I am trying to calibrate eye_on_base in order to find the transform between the camera and the base of the robot. When I launch the launch file, the GUI interface comes up and I press 'Take samples' but this error message shows up.

`[ERROR] [WallTime: 1528577063.870101] Error processing request: . canTransform returned after 10.0099 timeout was 10.
['Traceback (most recent call last):\n', '  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/dimitriskld/thesis_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_server.py", line 38, in take_sample\n    self.calibrator.take_sample()\n', '  File "/home/dimitriskld/thesis_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_calibrator.py", line 140, in take_sample\n    transforms = self._get_transforms()\n', '  File "/home/dimitriskld/thesis_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_calibrator.py", line 123, in _get_transforms\n    time = self._wait_for_transforms()\n', '  File "/home/dimitriskld/thesis_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_calibrator.py", line 110, in _wait_for_transforms\n    self.listener.waitForTransform(self.robot_base_frame, self.robot_effector_frame, now, rospy.Duration(10))\n', 'Exception: . canTransform returned after 10.0099 timeout was 10.\n']
Traceback (most recent call last):
 File "/home/dimitriskld/thesis_ws/src/easy_handeye/rqt_easy_handeye/src/rqt_easy_handeye/rqt_easy_handeye.py", line 104, in handle_take_sample
   sample_list = self.client.take_sample()
 File "/home/dimitriskld/thesis_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_client.py", line 34, in take_sample
   return self.take_sample_proxy().samples
 File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
   return self.call(*args, **kwds)
 File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 515, in call
   responses = transport.receive_once()
 File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 696, in receive_once`

I have already published a sample transform between robot_base_frame and robot_effector_frame using the command 
`rosrun tf static_transform_publisher x y z r p y robot_base_frame robot_effector_frame`
Also, should I create initially the frames in the tf tree? But these frames always change.

Thanks in advance!

**Comment by marcoesposito1988** [comment]
Closing for inactivity. If the problem persists, please comment and the issue will be reopened if appropriate.
