### ISSUE TITLE
The program suddenly crashes

### ISSUE THREAD

**Issue by WwYyFan** [IFL-CAMP/easy_handeye#21]
@marcoesposito1988  Hi ,I'm using it with a kinect v2,the program can start up, but it always suddenly crashes,and I don't konw where the problem is.

**Terminal error message**:
```
Traceback (most recent call last):
  File "/home/efun/work/kinect_test/src/easy_handeye/rqt_easy_handeye/src/rqt_easy_handeye/rqt_calibrationmovements.py", line 251, in handle_next_pose
    self.local_mover.execute_plan(plan)
  File "/home/efun/work/kinect_test/src/easy_handeye/rqt_easy_handeye/src/rqt_easy_handeye/rqt_calibrationmovements.py", line 110, in execute_plan
    raise RuntimeError("got crazy plan!")
RuntimeError: got crazy plan!
[calibration_mover-6] process has died [pid 29202, exit code -11, cmd /home/efun/work/kinect_test/src/easy_handeye/rqt_easy_handeye/scripts/rqt_calibrationmovements __name:=calibration_mover __log:=/home/efun/.ros/log/328d8954-f875-11e8-8d2c-4cedfbcaaae4/calibration_mover-6.log].
log file: /home/efun/.ros/log/328d8954-f875-11e8-8d2c-4cedfbcaaae4/calibration_mover-6*.log

*** Error in `python': double free or corruption (out): 0x00007f303c000e00 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f30c41fd7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f30c420637a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f30c420a53c]
/lib/x86_64-linux-gnu/libc.so.6(+0x39ff8)[0x7f30c41bfff8]
/lib/x86_64-linux-gnu/libc.so.6(+0x3a045)[0x7f30c41c0045]
python[0x51ea3f]
python[0x51bfd7]
python(PyErr_PrintEx+0x2d)[0x51b8fd]
/usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so(+0x1eaa68)[0x7f30be775a68]
/usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so(+0x127a52)[0x7f30be6b2a52]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x91468)[0x7f30be146468]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZNK14QMessageLogger5fatalEPKcz+0xa9)[0x7f30be147f69]
/usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so(+0x1eab82)[0x7f30be775b82]
/usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so(+0x1e9d7d)[0x7f30be774d7d]
/usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so(+0x1ea657)[0x7f30be775657]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x9a0)[0x7f30be369ee0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN15QAbstractButton7clickedEb+0x42)[0x7f30b69b82b2]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x257f44)[0x7f30b671af44]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x259559)[0x7f30b671c559]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN15QAbstractButton17mouseReleaseEventEP11QMouseEvent+0xf4)[0x7f30b671c6d4]
/usr/lib/python2.7/dist-packages/PyQt5/QtWidgets.x86_64-linux-gnu.so(+0x3247eb)[0x7f30b6ec67eb]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x668)[0x7f30b6660fc8]
/usr/lib/python2.7/dist-packages/PyQt5/QtWidgets.x86_64-linux-gnu.so(+0x3265eb)[0x7f30b6ec85eb]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7f30b661e05c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x959)[0x7f30b6623c19]
/usr/lib/python2.7/dist-packages/PyQt5/QtWidgets.x86_64-linux-gnu.so(+0x18aabe)[0x7f30b6d2cabe]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0xdb)[0x7f30be33b38b]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb+0x3c2)[0x7f30b6622b32]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1b85bb)[0x7f30b667b5bb]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1bab7b)[0x7f30b667db7b]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7f30b661e05c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x256)[0x7f30b6623516]
/usr/lib/python2.7/dist-packages/PyQt5/QtWidgets.x86_64-linux-gnu.so(+0x18aabe)[0x7f30b6d2cabe]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0xdb)[0x7f30be33b38b]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE+0x281)[0x7f30ba9cd4e1]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE+0x135)[0x7f30ba9cf1a5]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x28)[0x7f30ba9b2f08]
/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x6b200)[0x7f30aea92200]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7f30bf6ab197]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4a3f0)[0x7f30bf6ab3f0]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f30bf6ab49c]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7f30be3917cf]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x10a)[0x7f30be338b4a]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x9c)[0x7f30be340bec]
/usr/lib/python2.7/dist-packages/PyQt5/QtWidgets.x86_64-linux-gnu.so(+0x14dd1b)[0x7f30b6cefd1b]
python(PyEval_EvalFrameEx+0x5ca)[0x4bc4aa]
python(PyEval_EvalCodeEx+0x306)[0x4b9b66]
python(PyEval_EvalFrameEx+0x58e6)[0x4c17c6]
python(PyEval_EvalCodeEx+0x306)[0x4b9b66]
python(PyEval_EvalFrameEx+0x58e6)[0x4c17c6]
python(PyEval_EvalCodeEx+0x306)[0x4b9b66]

```

**log file : calibration_mover-6-stdout.log**
```
arguments:  Namespace(quiet=False)
unknowns:  []
^[[0m^[[0m
^[[33m^[[0m
^[[0m^[[0m
^[[0m^[[0m
^[[33m^[[0m
^[[0m^[[0m
^[[33m^[[0m
^[[0m^[[0m
```
**log file : calibration_mover-6.log**
```
[rospy.client][INFO] 2018-12-05 18:04:59,683: init_node, name[/calibration_mover], pid[29202]
[xmlrpc][INFO] 2018-12-05 18:04:59,683: XML-RPC server binding to 127.0.0.1:0
[xmlrpc][INFO] 2018-12-05 18:04:59,683: Started XML-RPC server [http://localhost:44619/]
[rospy.init][INFO] 2018-12-05 18:04:59,684: ROS Slave URI: [http://localhost:44619/]
[rospy.impl.masterslave][INFO] 2018-12-05 18:04:59,684: _ready: http://localhost:44619/
[rospy.registration][INFO] 2018-12-05 18:04:59,684: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2018-12-05 18:04:59,685: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2018-12-05 18:04:59,784: registered with master
[rospy.rosout][INFO] 2018-12-05 18:04:59,784: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-05 18:04:59,786: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-05 18:04:59,786: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2018-12-05 18:05:00,088: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2018-12-05 18:06:07,418: signal_shutdown [atexit]
[rospy.internal][INFO] 2018-12-05 18:06:07,420: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2018-12-05 18:06:07,420: atexit

```

**Comment by marcoesposito1988** [comment]
Hi @WwYyFan,

This is a safety measure. The program aborts if the planner finds a trajectory where the robot would move too much (for example, when one joint goes from -90 to 90 degrees). This could result in a big motion and a collision with the environment.

You can adjust the thresholds by passing a list as parameter (I hope it’s somewhere in the documentation, I have to check). But you should then keep an eye on the robot, and a finger on the red button! It is your responsibility to avoid that the robot crashes against something while it moves automatically.

**Comment by WwYyFan** [comment]
@marcoesposito1988  thanks a lot,I have changed the robot to another position,and the program is work now.Thanks.
