### ISSUE TITLE
How to get rqt_easy_handeye Gui to run???

### ISSUE THREAD

**Issue by 1gen100** [IFL-CAMP/easy_handeye#35]
I have this problem I'm not able to get my calibrator interface to pop up I only get this message, and tried to find a solution. The rviz GUI works fine, and the robot can be moved using the rviz program. Hope you can help:

Could not import "pyqt" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui_cpp/cpp_binding_helper.py", line 43, in <module>
    from . import libqt_gui_cpp_sip
ImportError: dynamic module does not define module export function (PyInit_libqt_gui_cpp_sip)

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/rqt_gui/rqt_gui", line 13, in <module>
    sys.exit(main.main())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/main.py", line 59, in main
    return super(Main, self).main(argv, standalone=standalone, plugin_argument_provider=plugin_argument_provider, plugin_manager_settings_prefix=str(hash(os.environ['ROS_PACKAGE_PATH'])))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/main.py", line 529, in main
    perspective_manager.import_perspective_from_file(self._options.perspective_file, perspective_manager.HIDDEN_PREFIX + os.path.basename(self._options.perspective_file))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/perspective_manager.py", line 342, in import_perspective_from_file
    self._convert_values(data, self._import_value)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/perspective_manager.py", line 403, in _convert_values
    self._convert_values(groups[group], convert_function)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/perspective_manager.py", line 400, in _convert_values
    keys[key] = convert_function(keys[key])
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/perspective_manager.py", line 410, in _import_value
    return QByteArray.fromHex(eval(value['repr(QByteArray.hex)']))
  File "<string>", line 1, in <module>
TypeError: arguments did not match any overloaded call:
  QByteArray(): too many arguments
  QByteArray(int, str): argument 1 has unexpected type 'str'
  QByteArray(Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'str'
[iiwa_kinect_handeyecalibration_eye_on_hand/namespace_dmri_w541_28293_3797793594356548394_rqt-18] process has died [pid 28475, exit code 1, cmd /opt/ros/kinetic/lib/rqt_gui/rqt_gui --clear-config --perspective-file /home/dmri/catkin_ws/src/easy_handeye/easy_handeye/launch/rqt_easy_handeye.perspective __name:=namespace_dmri_w541_28293_3797793594356548394_rqt __log:=/home/dmri/.ros/log/93e2877e-5b8d-11e9-acf4-54ee75886762/iiwa_kinect_handeyecalibration_eye_on_hand-namespace_dmri_w541_28293_3797793594356548394_rqt-18.log].
log file: /home/dmri/.ros/log/93e2877e-5b8d-11e9-acf4-54ee75886762/iiwa_kinect_handeyecalibration_eye_on_hand-namespace_dmri_w541_28293_3797793594356548394_rqt-18*.log

**Comment by marcoesposito1988** [comment]
```
Could not import "pyqt" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui_cpp/cpp_binding_helper.py", line 43, in 
from . import libqt_gui_cpp_sip
ImportError: dynamic module does not define module export function (PyInit_libqt_gui_cpp_sip)
```

Apparently on your computer there is a problem with the Qt Python dependencies. Have you used rosdep, as specified in the "Getting started" section of the README?

**Comment by marcoesposito1988** [comment]
Closing for lack of feedback
