### ISSUE TITLE
Support for noetic

### ISSUE THREAD

**Issue by galou** [IFL-CAMP/easy_handeye#91]
I'm not sure whether this is related to noetic but the rqt plugin cannot be loaded:
```
PluginManager._load_plugin() could not load plugin "rqt_easy_handeye/Hand-eye Calibration":
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 61, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 106, in load
    return class_ref(plugin_context)
  File "/home/gael/ros_ndt_ws/src/easy_handeye/rqt_easy_handeye/src/rqt_easy_handeye/rqt_easy_handeye.py", line 74, in __init__
    resp = self.client.list_algorithms()
  File "/home/gael/ros_ndt_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_client.py", line 83, in list_algorithms
    return self.list_algorithms_proxy()
TypeError: 'NoneType' object is not callable
```

So, my question is whether noetic is suppported.

**Comment by marcoesposito1988** [comment]
Hello @galou,

yes, ROS Noetic is absolutely supported.

What happens there is that you are opening the rqt plugin without the backend running. I encourage you to use the calibrate.launch file, by including it into your own after including the launch files that connect to your sensor and set up MoveIt.
